services:

  jenkins:
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile.jenkins 
    image: jenkins-docker:lts
    container_name: jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
    networks:
      - petclinic
    restart: unless-stopped
    depends_on:
      - docker

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-client:/certs/client
      - dind-storage:/var/lib/docker
    networks:
      - petclinic
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube:/opt/sonarqube/data
    networks:
      - petclinic
    restart: unless-stopped

networks:
  petclinic:
    name: petclinic

volumes:
  jenkins:
    name: jenkins
  sonarqube:
    name: sonarqube
  docker-certs-client:
  dind-storage: