services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - petclinic
    restart: unless-stopped

  jenkins-java17jdk:
    image: jenkins/inbound-agent:latest-jdk17
    container_name: jenkins-java17jdk
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: jenkins-java17jdk
      JENKINS_AGENT_WORKDIR: /home/jenkins/java17jdk
      JENKINS_SECRET: ${JENKINS_JAVA17_JDK}
    networks:
      - petclinic
    volumes:
      - java17jdk-m2:/home/jenkins/.m2
    restart: unless-stopped

  jenkins-dockercli:
    build:
      context: .
      dockerfile: ./agents/Dockerfile.docker-cli
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: jenkins-dockercli
      JENKINS_AGENT_WORKDIR: /home/jenkins/dockercli
      JENKINS_SECRET: ${JENKINS_DOCKER_CLI}
    container_name: jenkins-dockercli
    volumes:
      - docker-certs-client:/certs/client:ro
    networks:
      - petclinic
    restart: unless-stopped
    depends_on:
      - docker
    
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-client:/certs/client
      - dind-storage:/var/lib/docker
    networks:
      - petclinic
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube:/opt/sonarqube/data
    networks:
      - petclinic
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus:/nexus-data
    networks:
      - petclinic
    restart: unless-stopped

networks:
  petclinic:
    name: petclinic

volumes:
  jenkins:
    name: jenkins
  sonarqube:
    name: sonarqube
  docker-certs-client:
  dind-storage:
  nexus:
  java17jdk-m2: