services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - petclinic
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube:/opt/sonarqube/data
    networks:
      - petclinic
    restart: unless-stopped

networks:
  petclinic:
    name: petclinic

volumes:
  jenkins:
    name: jenkins
  sonarqube:
    name: sonarqube