# This is jenkins agent with docker cli installed
FROM docker:cli AS dockercli
FROM jenkins/inbound-agent:latest-jdk17
USER root
COPY --from=dockercli /usr/local/bin/docker /usr/local/bin/docker
USER jenkins